/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.DAOFuncionario;
import DAO.DAOUsuario;
import Modelo.Funcionario;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Marques, Lucas Chagas, Matheus Peixoto, Nicolas Mendes, Pedro Henrique de
Oliveira, Pedro Morais
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private DAOFuncionario daoFuncionario;
    private DAOUsuario daoUsuario;

    
    /**
     * Creates new form TelaLoginFuncionario
     */
    public MenuPrincipal() {
        initComponents();
        
        meuInitComponents();
    }

    private void meuInitComponents(){
        daoFuncionario = new DAOFuncionario();
        daoUsuario = new DAOUsuario();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoLogin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        radioFuncionario = new javax.swing.JRadioButton();
        radioUsuario = new javax.swing.JRadioButton();
        radioAdministrador = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Funcionário");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login  ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID do funcionário, usuário ou administrador:");

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        tipoLogin.add(radioFuncionario);
        radioFuncionario.setText("Funcionário");

        tipoLogin.add(radioUsuario);
        radioUsuario.setText("Usuário");

        tipoLogin.add(radioAdministrador);
        radioAdministrador.setText("Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioFuncionario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioUsuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioAdministrador)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtId)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFuncionario)
                    .addComponent(radioUsuario)
                    .addComponent(radioAdministrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(radioFuncionario.isSelected())
            loginFuncionario();
        
        else if(radioUsuario.isSelected())
            loginUsuario();
            
        else if(radioAdministrador.isSelected())
            loginAdministrador();
            
        else
            JOptionPane.showMessageDialog(this, "Informe o tipo de usuário", "Erro no Login",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnEntrarActionPerformed
    
    private void loginFuncionario(){
        try{
            int id = Integer.parseInt(txtId.getText());
            Funcionario func = daoFuncionario.localizar(id);
            
            if(func != null){
                TelaMenuFuncionario menuFuncionario = new TelaMenuFuncionario(func);
                menuFuncionario.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "ID de funcionário não encontrado.", "Erro no Login",JOptionPane.ERROR_MESSAGE);
                reiniciaForm();
            }
        }catch(Exception ex){
            System.err.println("\nExcecao: " + ex + "\n");
            JOptionPane.showMessageDialog(this, "Digite apenas números para o id.", "Erro",JOptionPane.ERROR_MESSAGE);
            reiniciaForm();
        }        
    }
    
    private void loginUsuario(){
        try{
            int id = Integer.parseInt(txtId.getText());
            Usuario user = daoUsuario.localizar(id);
            System.out.println("Usuario: "+user);
            
            if(user != null){
                TelaMenuUsuario menuUsuario = new TelaMenuUsuario(user);
                menuUsuario.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "ID de usuário não encontrado.", "Erro no Login",JOptionPane.ERROR_MESSAGE);
                reiniciaForm();
            }
        }catch(Exception ex){
            System.err.println("\nExcecao: " + ex + "\n");
            JOptionPane.showMessageDialog(this, "Digite apenas números para o id.", "Erro",JOptionPane.ERROR_MESSAGE);
            reiniciaForm();
        }
    }
    
    private void loginAdministrador(){
        try{
            int id = Integer.parseInt(txtId.getText());
            
            if(id == 123456){
                TelaMenuADM telaAdm = new TelaMenuADM();
                telaAdm.setVisible(true);
                this.setVisible(false);
            }
            
            else{
                JOptionPane.showMessageDialog(this, "ID do administrador inválido.", "Erro no Login",JOptionPane.ERROR_MESSAGE);
                reiniciaForm();
            }
        }catch(Exception ex){
            System.err.println("\nExcecao: " + ex + "\n");
            JOptionPane.showMessageDialog(this, "Digite apenas números para o id.", "Erro",JOptionPane.ERROR_MESSAGE);
            reiniciaForm();
        }
    }
    
    private void reiniciaForm(){
        txtId.setText("");
        txtId.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radioAdministrador;
    private javax.swing.JRadioButton radioFuncionario;
    private javax.swing.JRadioButton radioUsuario;
    private javax.swing.ButtonGroup tipoLogin;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
